### ISSUE TITLE
'Download failed' for everything

### ISSUE THREAD

**Issue by GratefulforGIA** [Ascoware/get-iplayer-automator#124]
Thanks to everyone involved in making this programme brilliant. I'd be grateful to know if there's any way around my current difficulty:

-Using GiA v1.10.2 in the UK
- Series update is working and titles appear in the download queue
- when I hit 'start', the status of each item in the download queue changes, one by one, to 'download failed' (same for BBC and ITV)
- if I try to download from selected webpage, the title comes up, but again, the download fails. The diagnosis is: 'problem unknown: Please submit a bug report...'

Thanks for any advice.

**Comment by jchhenderson** [comment]
which programmes?

**Comment by GratefulforGIA** [comment]
Hi - thanks. Here's what's failing at the moment (others are, too, but I downloaded them via Downie (couldn't believe how slow it was in comparison to GIA!).

- Call the midwife s7, e8
-Civilisations, all episodes
-Shetland, s4, e5
-Keeping Faith, s1, e5.

All the best.

**Comment by jchhenderson** [comment]
hmm, most of those (listed below) worked for me (I am using 1.10.2 in the UK on a Mac)
- Call the midwife
- Shetland
- Keeping Faith

I have just re-downloaded "call the midwife" to double check - no problems - downloaded in ~2 minutes.

...sounds dumb, but have you restarted your Mac recently (if not can you?)

**Comment by GratefulforGIA** [comment]
Strange. Will restart now.

**Comment by GratefulforGIA** [comment]
Same again after restart - all failing. Thanks anyway.

**Comment by jchhenderson** [comment]
sorry to hear that :/

**Comment by ElsonRoa** [comment]
All BBC downloads on my version of GIA are failing too. Also radio broadcasts. I tried updating from 1.10.1 to 1.10.2 with no change. I am using Mac OSX 10.11.6. 

It does not appear to be an IP/geolocation problem since I am able to DL from the BBC using get_iplayer Web PVR Manager 3.12

**Comment by skovatch** [comment]
Not sure what else to suggest here. I'm having no issues with BBC radio or TV downloads... maybe try turning on the Verbose option and see if you can get more information in the log window?

**Comment by Don-Kuwait** [comment]
I get roughly the same issue, and it has just started this morning, one additional symptom, the Status first indicates Available: None, then jumps to Download Failed

**Comment by Don-Kuwait** [comment]
I have discovered my VPN is not functioning correctly, although the link is made, it doesnt recognise me as being in the UK

**Comment by GratefulforGIA** [comment]
Hi, all. Everything is still failing for me. Using 'get current webpage', the name of the programme appears but then changes to 'Unknown: PID not found... Download failed.' I did start to wonder if there was some problem with GiA not recognising that I'm in the UK. I'll keep installing updates, and will keep trying, but I'm getting a sinking feeling. Thanks or the solidarity, at any rate.

**Comment by PhoolR** [comment]
I'm getting 'download failed' for BBC TV programmes. Currently, ITV and BBC Radio programmes seem to be working fine. This was working until today (and I'm not sure if it was working after the 1.13 update at all, but definitely was working before it).

I'm using a dedicated IP VPN, Mac OS X 10.12.6 and GiPA v1.13

> Downloading Show 1/6:
> 
> BBC Download (ID=b09yn6xj): Downloading Troy: Fall of a City: Series 1 - Twelve Days
> INFO: 1 total programmes
> WARNING: No media streams found for requested programme versions and recording modes.
> WARNING: The programme may no longer be available - check the iPlayer site.
> BBC Download (ID=b09yn6xj): Troy: Fall of a City: Series 1 - Twelve Days Failed
> 
> Downloading Show 2/6:
> 
> BBC Download (ID=b09xymcn): Downloading The Assassination of Gianni Versace - American Crime Story: Series 1 - Don't Ask Don't Tell
> INFO: 1 total programmes
> WARNING: No media streams found for requested programme versions and recording modes.
> WARNING: The programme may no longer be available - check the iPlayer site.
> BBC Download (ID=b09xymcn): The Assassination of Gianni Versace - American Crime Story: Series 1 - Don't Ask Don't Tell Failed

**Comment by PhoolR** [comment]
```Downloading Show 1/6:BBC Download (ID=b09yn6xj): Downloading Troy: Fall of a City: Series 1 - Twelve DaysINFO: 1 total programmesWARNING: No media streams found for requested programme versions and recording modes.WARNING: The programme may no longer be available - check the iPlayer site.BBC Download (ID=b09yn6xj): Troy: Fall of a City: Series 1 - Twelve Days FailedDownloading Show 2/6:BBC Download (ID=b09xymcn): Downloading The Assassination of Gianni Versace - American Crime Story: Series 1 - Don't Ask Don't TellINFO: 1 total programmesWARNING: No media streams found for requested programme versions and recording modes.WARNING: The programme may no longer be available - check the iPlayer site.BBC Download (ID=b09xymcn): The Assassination of Gianni Versace - American Crime Story: Series 1 - Don't Ask Don't Tell Failed```

**Comment by jchhenderson** [comment]
Hi @PhoolR 

I have just checked "Troy s01e07 - Twelve days" and it is downloading fine for me.

Are you no a VPN?

**Comment by skovatch** [comment]
Turn on verbose mode and make sure get_iplayer is trying to get the file. The BBC may have figured out your connections are via a VPN and is blocking your VPN provider.

**Comment by PhoolR** [comment]
As mentioned, I'm on a VPN and it's a dedicated IP address (so should work fine with iPlayer). I hope that this has now not stopped working as will be very frustrating.

**Comment by jchhenderson** [comment]
@PhoolR - sorry - missed the VPN comment.

...everything seems fine at the BBC end, so I am guessing it is your VPN.

**Comment by PhoolR** [comment]
That didn't work, and going to the iPlayer site it does seem to have blocked my VPN as it says I'm out of the country. That was a waste of money for a dedicated IP then! Not sure how they managed to figure that out (maybe posting on here while it was turned on was not a good idea?).

**Comment by hugofalkman** [comment]
Turn on verbose mode -- if you see the ERROR 403 forbidden message its your VPN even if it's a dedicated IP address. Also I have found that BBC now puts cookies warning you are outside UK, so you have to close BBC site, go to Safari preferences, privacy tab, manage website data and delete all for all bbc sites.

**Comment by skovatch** [comment]
No, they can't track your activity elsewhere. :-) VPN works by giving you a network address that makes it look like you're in the UK. But, depending on implementation, it can look like a lot of traffic is coming from one address or a small range of addresses, so they can filter connections from those IP addresses and send you back the 'not in the UK' responses.

**Comment by Vangelis66** [comment]
Happy Easter Sunday all!

The BBC iPlayer team has been having a blacklisting frenzy for the past week or so :rage:
This time around, not only did they go after some well-advertised commercial VPN providers, but they vehemently also targeted other means of geoblock evasion, like free and commercial HTTP(S) proxies, on-line proxies and VPS providers; I had one free proxy that worked for years + one commercial proxy going strong for the past 3 years, both were blocked on Good Wednesday (not as "good", as things turned out... ); and make no mistake, I have posted about this in the previous GiA tracker, sites of BBC iPlayer downloading tools are being monitored, people should not name in detail and out in the open what they use to fetch from the beeb when overseas... 

The mandatory sign-in requirement to iPlayer is a big leap for them to track down illicit access; they are now employing means similar to what Hulu/Netflix e.a are using in the States to block access (more [here](https://techcentral.co.za/how-netflix-is-blocking-vpns/63882/)) ; logged-in users are being "tagged"; if you remained logged-in after you switched off your VPN or logged-in even once from your true IP, this is being recorded and kept for future comparison, when you attempt streaming with your same BBC ID but originating from your "pretend" UK IP. :fearful:

> Also I have found that BBC now puts cookies warning you are outside UK

Yes, this is correct; geo-location cookie put in your browser by fig API: 
https://fig.bbc.co.uk/frameworks/fig/2/fig.js?callback=orb.orb_fig
If you access from overseas, then response will have `'uk':0,` in the second line, else it'll be `'uk':1,` But this is only a first soft block, what they are geo-filtering mainly is the mediaselector API; e.g. try 

http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b07dpsp5

in your browser with your VPN on; if you get 
```xml
<mediaSelection><error id="geolocation"/></mediaSelection>
```
this means your IP has been blacklisted, even if it's a dedicated IP one...

I realise the wishes of Scott are to not offer support pertaining to non-UK access; while I understand this view in the sense the software itself can't be modified to counter the media provider's blocks, GiA overseas users (who, undoubtedly, are many in numbers - after all, the original creator is an American) should be kept well informed and cautioned against longterm/serious monetary commitments with geofilter-evasion providers, at this perilous times when BBC/ITV are getting really tough... 

... And just a heads-up: In a little more than a month's time, the BBC will take down their "json" playlist/metadata URLs, the only remaining automated means for GiP (hence GiA) to retrieve vPID and stream data for a particular BBC show, _without actually using a BBC ID to access that info_; when that time comes, the GiP maintainer will have to re-write the code, no doubt a BBC ID login will then become mandatory for GiP/GiA too, so that GiP could web-scrape needed info from page content offered to signed-in only iPlayer users... Or I got it all wrong and things won't be that dire.... 
In any case, things are going to become more difficult/risky for overseas users when both a BBC ID (which also contains personal data attached to it, e.g. e-mail / home address) and a fake UK IP will be required :unamused: :worried:  

@skovatch 
In a previous exchange, you hinted about a "discussion" place/forum/blog etc., where things like this (which are not strictly software bugs and don't belong in an issue tracker) could be discussed amongst users :smirk:; any light coming from the end of the tunnel ? (no reference whatsoever to VPN/SSH tunnels! :grinning: )

**Comment by PhoolR** [comment]
Okay, thanks Vangelis66. And I understand that we probably shouldn't be talking about this here so I appreciate it and won't go further.

It's a shame that BBC does this and offers no way for expats overseas to view their content. I would pay a license fee if they offered it! My link home looks broken now.

**Comment by skovatch** [comment]
I haven't really had time to research setting up a forum or discussion group site.

My only reason for shutting down discussions or bugs that amount to "I can't download because I'm getting blocked/getting an access error/etc" is that there is _nothing_ that GiA or get_iplayer can do to address this, and even if there was, I have no intention of adding it. 

It is solely an issue between you and whomever is offering the ability to look like you are connecting from the UK. I don't have the time or inclination to help people sort out setup or offer any other advice regarding non-UK-based access.

Having said that, comments involving geolocation and/or blocking techniques and future decisions by the networks are fine by me. I do hope that you are raising these concerns with the maintainers of get_iplayer and youtube-dl, because ultimately they are the ones who will have to deal with it. Sure, GiA will have to adapt if those tools change significantly, but I'll let someone with more free time figure out how to deal with the actual downloading of content.

**Comment by PaulW78** [comment]
No BBC iPlayer episodes will download for me.

I'm using the 'Use Current Webpage' option as I've always done, and it brings the correct episode name through to to the top screen, so I click 'Add to Queue' but when I press 'Start' the download instantly fails saying 'Unknown: PID Not Found', even though it shows the PID on the left hand side under the 'PID' column.

I'm not using a VPN because I'm based in the UK, so it should work. It plays fine via the actual iPlayer website. Can anyone advise?

**Comment by jchhenderson** [comment]
@PaulW78 

I just tried to download a random episode and it worked fine for me.

What version of GiA are you running?
Can you give an example of an epodes that will not download?

thanks,
James.

**Comment by PaulW78** [comment]
@jchhenderson 
I'm using v1.13.1 (20180404002)

No episodes will download for me. An example is PID b09w375q which is for Troy: Fall of a City Series 1: 4. Spoils of War

Screenshots:
![screenshot1](https://user-images.githubusercontent.com/38182746/38468775-a368cbd4-3b42-11e8-8531-9ec92d2ae57b.png)

![screenshot2](https://user-images.githubusercontent.com/38182746/38468774-a35208d6-3b42-11e8-82ba-f9be204c14a4.png)

![screenshot3](https://user-images.githubusercontent.com/38182746/38468773-a339f03e-3b42-11e8-801c-29e62078c407.png)

**Comment by jchhenderson** [comment]
odd.  That episode is working fine for me.  Something. else is going on...
![screen shot 2018-04-08 at 15 53 53](https://user-images.githubusercontent.com/34644672/38468954-4c816bf2-3b45-11e8-9a43-5aa64800f8f7.png)
![screen shot 2018-04-08 at 15 54 53](https://user-images.githubusercontent.com/34644672/38468956-51604bd4-3b45-11e8-8bcd-6f0806d711c3.png)

**Comment by PaulW78** [comment]
@jchhenderson Strange. I haven't changed anything recently apart from updating the version, but I had this issue before the latest version. In fact recently the whole program kept crashing as soon as I opened it.

Have you got any non-standard settings activated?

**Comment by skovatch** [comment]
When I see "Unknown: PID not found" in the queue, my first thought is that your cache files are corrupted in some way. Quit the app, then go to ~/Library/Application Support/Get iPlayer Automator/ and delete itv.cache, tv.cache, and radio.cache. Then start the app again.

**Comment by jchhenderson** [comment]
no, I have nothing special activated.

**Comment by PaulW78** [comment]
@skovatch That worked. Thank you so much!

**Comment by skovatch** [comment]
For others coming in late: a good rule of thumb is that if you see "Unknown: PID not found", throw away your cache files and start the app again to rebuild them. I will add a TODO for myself to add this as a menu item or advanced option in the preferences so you don't have to go into Terminal to do it.
