### ISSUE TITLE
Cache update not working

### ISSUE THREAD

**Issue by PhoolR** [Ascoware/get-iplayer-automator#138]
After the latest update today (1.11.2) the cache update seems to have stopped working for me. None of the PVR is coming through and when I do a manual search for anything it reports 'No Shows Found'.

EDIT: I did a force cache update and this worked. Not sure if it will need to be done like this all the time or if this has now fixed the issue. Time will tell.

**Comment by jchhenderson** [comment]
I am having this same issue. Please also see #135 which may (or may not) be a related issue.

However today, I got something else quite interesting: GiA reported the wrong series: It reported it had found Lewis, but in fact downloaded Morse - the PID's were the same though (and Morse was correct).
![screen shot 2018-03-21 at 18 18 18](https://user-images.githubusercontent.com/34644672/37760169-cd187706-2dad-11e8-840b-04823ec7b6c9.png)
![screen shot 2018-03-21 at 18 19 15](https://user-images.githubusercontent.com/34644672/37760171-cf8ff248-2dad-11e8-96bd-b1c70988acd8.png)
![screen shot 2018-03-21 at 18 20 21](https://user-images.githubusercontent.com/34644672/37760174-d21bb86c-2dad-11e8-9d38-b95b91cc4110.png)

**Comment by sleaux-meaux** [comment]
Invalid records are being added to the ITV cache, which cause the search to fail no matter what search term you use. For me, this seems to always happen on the first refresh on startup. A forced update often corrects the problem, but not always. It may take 2-3 attampts. I haven't seen any pattern to the corruption. This doesn't appear to affect BBC caches, which are populated by get_iplayer.

**Comment by Mimpy** [comment]
See issue 137 as reported yesterday..

**Comment by Mimpy** [comment]
This is now affecting my BBC caches also. Masterchef is available as was The Repair Shop but no show in the queue after regular and forced cache update. FYI...

**Comment by sleaux-meaux** [comment]
You may be encountering this:

https://forums.squarepenguin.co.uk/thread-1707.html

**Comment by Mimpy** [comment]
That's it... Thanks Sleaux-Meaux.

**Comment by skovatch** [comment]
Since caching ITV episode data is so fast, there's no need to do a lot of updating of the existing cache with the new shows. I will change it so that every update is just be a full update and then you always have what's available. It will make the code simpler, too.

**Comment by PhoolR** [comment]
Just to clarify, I was not only talking about ITV caches (as many seem to be highlighting) but ALL caches. In fact, I don't have any ITV programmes in my PVR, it's all BBC (and mostly Radio).

Mimpy, Issue 137 wasn't available for me to see (it appears to have been closed for some reason), plus as I've said, I'm not just highlighting an issue with ITV caches (which have always been problematic for me anyway and I usually just add those manually).

When I did a refresh today it again didn't add anything, and even after doing a forced cache update it still hasn't added.

**Comment by skovatch** [comment]
Please see the link above -- BBC Radio caches are broken due to a change in show pages at the BBC. That will need a new version of get_iplayer, which they are expecting to release over this coming weekend. I will need to merge it into GiA.

**Comment by bevanting** [comment]
Hi again, sorry to be a pain but I now have 1.11.3 and I've done force cache update quite a few times and I'm still getting "Unknown: PID Not Found". The Forced Cache Update trick worked once in 1.11.2. Hasn't worked since. I've even deleted 1.11.2 and re-download and installed 1.11.3. Is anyone else having this problem?

**Comment by skovatch** [comment]
It's also possible that you need to delete and re-add the show that says PID Not Found, since it may be referring to the old cache entries.

**Comment by bevanting** [comment]
I’ve re-added but to no avail. Will try the other tip when I get home. Thanks. 

Regards,
Bevan

 bevanting@gmail.com
 www.bevansbubble.com
   

This Message may contain confidential and privileged information. If received in error, please reply to advise the sender of the error and delete this message. Thank you.


Sent from my iPhone

On 24 Mar 2018, at 15:04, Scott Kovatch <notifications@github.com> wrote:

It's also possible that you need to delete and re-add the show that says PID Not Found, since it may be referring to the old cache entries.

**Comment by bevanting** [comment]
Nope clearing the cache didn’t work. 

I checked that the cache was deleted (and wasn’t added back) and deleted and re-added the show. 

The show info appears when I clicked Current Webpage but as soon as I click process PID it changed to “unknown”. 
☹️ 

Do I need to delete the cache and empty the trash? 

Regards,
Bevan

 bevanting@gmail.com
 www.bevansbubble.com
   

This Message may contain confidential and privileged information. If received in error, please reply to advise the sender of the error and delete this message. Thank you.


Sent from my iPhone

On 24 Mar 2018, at 15:03, Scott Kovatch <notifications@github.com> wrote:

I would recommend deleting ~/Library/Application Support/Get iPlayer Automator/itv.cache and running the app again. Until 1.11.3, the cache file was constantly being corrupted when saved to disk, so you can't trust it.

**Comment by skovatch** [comment]
Well, if you delete the cache and click Process PID it won't be found, since all that button does is search the cache. Just leave the show in the download queue, quit the app, and launch it again. The cache will rebuild itself on next launch.

**Comment by bevanting** [comment]
I see. Thanks for the tip. 

Regards,
Bevan

 bevanting@gmail.com
 www.bevansbubble.com
   

This Message may contain confidential and privileged information. If received in error, please reply to advise the sender of the error and delete this message. Thank you.


Sent from my iPhone

On 24 Mar 2018, at 15:25, Scott Kovatch <notifications@github.com> wrote:

Well, if you delete the cache and click Process PID it won't be found, since all that button does is search the cache. Just leave the show in the download queue, quit the app, and launch it again. The cache will rebuild itself on next launch.

**Comment by PhoolR** [comment]
I also now have 1.11.3 but still no new shows added? Am I being stupid? When I did a search for programmes it has only shows up to March 21, nothing after that. I have deleted all the cache files and now there are no results. Was this release supposed to be a fix for this issue or is that still pending? Thanks for the quick work anyway!

**Comment by bevanting** [comment]
Well, I've closed the app, re-open it, deleted the cookies, and nothing worked. I've checked, no new cache file created. The cookies.desktop is deleted and re-created every time I clicked "Process PID". 
But whatever I've tried, it's still showing "Unknown ...". I've also deleted the entry and re-created it.

Can we have an option in Preferences to just use the title from "Current Webpage"? I'm quite happy with that title.

**Comment by bevanting** [comment]
OK what worked for me in the end was this:

Delete existing GiA and all folders and settings.
Download and install current version.
Go to settings and make sure ITV TV is ticked for "Items to cache"

THEN, when downloading an entry, it worked!!

Hope this helps others.

**Comment by raythw** [comment]
That didn't work for me, I'm afraid. No shows on BBC TV, even using a search for a valid name. Looks as though Sleaux-Meaux is right...

**Comment by raythw** [comment]
PS: You can still use the "Use Current Webpage" to download a program. It's just the cache and its search facility that isn't working. I've tried earlier versions of GiA with all the old files deleted but nothing works. A HUGE pain...

**Comment by raythw** [comment]
Further to this, if I look in the tv.cache file after a forced cache update it shows no entries, whereas that for ITV does...

**Comment by skovatch** [comment]
Oh, that means the BBC cache problems from get_iplayer are now affecting the TV pages too. I did notice they have a slightly different design with new fonts and the like; it could be that the underlying HTML changed too. We’ll just have to wait for dinkypumpkin to update, and hopefully it won’t be a pain to integrate like 3.06 was.

**Comment by sleaux-meaux** [comment]
@raythw: Don't delete a file in the application support directory unless you know for a fact there is something wrong with it. GiA was corrupting the itv.cache file, but that was the only file affected. get_iplayer hasn't been able to update tv.cache since Thursday, and by deleting the file you lost all the entries accrued through the last update you performed before then. Unless you backed up the file, you won't be able restore all of the previous entries with GiA.

**Comment by raythw** [comment]
@sleaux-meaux: Many thanks for the extra information. I had assumed that the tv.cache file would be reconstructed once GiA is fully working again. In any event, our friends at Apple gave us Time Machine, so I've retrieved the earlier tv.cache file, just to be on the safe side!

**Comment by skovatch** [comment]
Fixed in v1.12.0

**Comment by naq59** [comment]
Fantastic! Thanks so much Scott for the hard and really quick work.

**Comment by raythw** [comment]
Great job!
