### ISSUE TITLE
GIA downloading to 99% then not finishing or adding to iTunes. 

### ISSUE THREAD

**Issue by stevenfld** [Ascoware/get-iplayer-automator#179]
![screen shot 2018-06-01 at 4 25 01 pm](https://user-images.githubusercontent.com/39712913/40867647-955f5bd4-65e0-11e8-9433-cb8cc1273ffd.png)

Per above screenshot GIA is downloading to 99% then stopping. It does not finish or add the show to iTunes.  Any suggestions?

**Comment by skovatch** [comment]
For the short term, turn off "Get higher-quality audio" and restart the download. Turning on verbose mode might reveal some more information, but it sounds like either get_iplayer is stalling out or GiA is not detecting the end of the download.

**Comment by sleaux-meaux** [comment]
"Get higher-quality audio" is not going to be relevant in your case. That feature is defunct due to changes by the BBC, and it doesn't apply to your example, anyway. However, you may have several other problems:

1. You appear to be downloading DASH streams. That is most likely due to HLS streams being blocked for your VPN, while DASH streams are not.  If you select "Force get_iplayer to ignore DASH video" in preferences and you are unable to download any programmes, that could be the problem.  I don't think there is anything you can do about it except find another VPN.
2.  GiA is broken with respect to tracking download progress for DASH because it doesn't correctly parse get_iplayer output. After downloading audio, It never switches over to display progress for the video part. If you look in your output directory you should see the video file increasing in size as it is downloaded, but if you open the GiA log window you won't see any progress tracking. If you don't see a video file, or it isn't increasing in size, then something more fundamental is wrong.
3. For DASH downloads, GiA unfortunately forces a re-encoding of the audio and video files to produce the final output. You should see the invocation of ffmpeg noted in the GiA log window. The re-encoding process can take a very long time, perhaps 50%-100% of the programme duration. You may not be waiting long enough for it to finish. This needless re-encoding should go away when GiA is upgraded to the latest version of get_iplayer. The finish of the download would be noted in the GiA log window, and with a system notification (by default). If you don't see any of those things in the log window, then the download really is dying, and something else is wrong.

**Comment by skovatch** [comment]
> GiA is broken with respect to tracking download progress for DASH because it doesn't correctly parse get_iplayer output. After downloading audio, It never switches over to display progress for the video part.

Please provide an example of this. This is not the first time you've said this without any additional explanation. Since you seem to know everything about this application, it would be useful for all of us.

**Comment by skovatch** [comment]
Also, --hls-hq-audio is still an option in the latest get_iplayer, and that fetches an additional audio stream that gets re-combined with the video. Turning that off will tell get_iplayer to not fetch that.

**Comment by sleaux-meaux** [comment]
It seems you would rather shoot the messenger rather than take responsibility for your code. Still, lest I be thought uncharitable:

https://github.com/Ascoware/get-iplayer-automator/blob/master/BBCDownload.m#L582

Surely it's obvious what is wrong there, and surely it's obvious why that makes the progress output disappear for the video download:

```
95.4%     2.40 MB / ~2.52 MB (00:03:23 / 00:03:31) [   53 / 55] @   4.8 Mb/s ETA: 00:00:00 (dvfxsd1/ll) [audio]
96.4%     2.43 MB / ~2.52 MB (00:03:23 / 00:03:31) [   53 / 55] @   4.9 Mb/s ETA: 00:00:00 (dvfxsd1/ll) [audio]
97.5%     2.46 MB / ~2.52 MB (00:03:27 / 00:03:31) [   54 / 55] @   4.9 Mb/s ETA: 00:00:00 (dvfxsd1/ll) [audio]
98.5%     2.48 MB / ~2.52 MB (00:03:31 / 00:03:31) [   55 / 55] @   5.0 Mb/s ETA: 00:00:00 (dvfxsd1/ll) [audio]
99.6%     2.51 MB / ~2.52 MB (00:03:31 / 00:03:31) [   55 / 55] @   5.0 Mb/s ETA: 00:00:00 (dvfxsd1/ll) [audio]
INFO: Downloaded: 2.52 MB (00:03:31) [55] in 00:00:04 @ 5.04 Mb/s (dvfxsd1/ll) [audio]
INFO: Finished downloading to file: /Users/user1/Movies/TV Shows/Weather for the Week Ahead/Weather for the Week Ahead - 2018-06-01 ((dvfxsd)).audio.m4a
INFO: Begin downloading at: 0.00 MB (00:00:00) [1]
INFO: Downloaded: 41.60 MB (00:03:31) [55] in 00:00:10 @ 33.28 Mb/s (dvfxsd1/ll) [video]
INFO: Finished downloading to file: /Users/user1/Movies/TV Shows/Weather for the Week Ahead/Weather for the Week Ahead - 2018-06-01 ((dvfxsd)).video.m4v
```

--hls-hq-audio only applies with certain streams which have virtually disappeared from iPlayer, rendering it defunct for all intents and purposes. Those streams are not available for the programme in the OP example, so --hls-hq-audio is ignored and is irrelevant to his case.

**Comment by skovatch** [comment]
What does that prove? Download any radio program and you will see that it correctly handles "[audio]". Look at line 7480 of get_iplayer, and you will see it only produces [audio+video] and [audio], which this line handles.

I don't see how you can automatically assume the OP is getting DASH video. In a separate post he indicated he was using "Get Higher Quality Audio", which is why I suggested he turn it off and try again.

**Comment by sleaux-meaux** [comment]
> What does that prove? Download any radio program and you will see that it correctly handles "[audio]". Look at line 7480 of get_iplayer, and you will see it only produces [audio+video] and [audio], which this line handles.

It proves you need to learn a thing or two about get_iplayer. Start from here and you should be able to figure it out:

https://github.com/Ascoware/get-iplayer-automator/blob/master/get_iplayer#L8149

> I don't see how you can automatically assume the OP is getting DASH video. 

There are only two ways I see to get "Audio download" in the status entry for a TV download, as shown in the screenshot: Use --hls-hq-audio or download DASH. I already know that the former does not apply in this case, so it must be the latter. I also know that with DASH downloads the "Audio download" status value always always appears to stick at 99% because the video progress doesn't kick in. It would require a rather precisely repetitive failure for that to happen with --hls-hq-audio.

> In a separate post he indicated he was using "Get Higher Quality Audio", which is why I suggested he turn it off and try again.

For the example given it doesn't matter if "Get Higher Quality Audio" is selected in preferences or not. It would simply be ignored. Start from here and you should be able to figure out why:

https://github.com/Ascoware/get-iplayer-automator/blob/master/get_iplayer#L7510

**Comment by skovatch** [comment]
> It proves you need to learn a thing or two about get_iplayer. Start from here and you should be able to figure it out:

No. I don't have time for guessing games with you. This is an open source project, and I'm going to assume you are programmer. In the future I want you to do the following: first, provide clear steps on how to reproduce the problem. If you see a problem in the code, create a branch, make your change, and submit a pull request with your changes. I'll review it and merge it back in.

That said, I did do a test build that forces DASH downloads, and once I did that I was able to see the [video] output in the INFO line. Had you done any of these things beforehand, you would have saved all of us a lot of time, and I wouldn't be forced to play 20 questions with you to fix this problem. I would also be a lot less frustrated with you right now, too.

I will try to react to these situations better in the future. I hope you will do the same when offering suggestions.

**Comment by skovatch** [comment]
For the original poster (@stevenfld), then: you can either force GiA to ignore DASH video, or upgrade to 1.13.5. You won't see the video download progress, but it will eventually finish.

**Comment by sleaux-meaux** [comment]
>No. I don't have time for guessing games with you.

So I describe the problem, tell you how to find it, and that constitutes a "guessing game"? You have an odd notion of what constitutes a guess. Nobody cares if you don't know the ins and outs of the application, but you can't sneer at others for pointing out problems.

>If you see a problem in the code, create a branch, make your change, and submit a pull request 

It shouldn't require a pull request for you - or any developer - to own your mistakes. If you don't have the time - or don't want to invest the time - to investigate, then just ignore the issue. Nobody expects a response if you have nothing to offer. 

> That said, I did do a test build that forces DASH downloads, and once I did that I was able to see  and once I did that I was able to see the [video] output in the INFO line. Had you done any of these things beforehand

That is ridiculously patronising and betrays a pretty low opinion of your users. How do you suppose I could see what was happening? If you had bothered to do as I did and replicate the OP's problem before weighing in, we wouldn't be here.

> I will try to react to these situations better in the future.

Life is too short. Rest safe in the knowledge that I will ignore every keystroke from you in the future and I will make no reference to anything you do or say. I trust you will do likewise.
