### ISSUE TITLE
BBC Planet Earth programmes only downloading in SD

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#214]
Planet Earth ep 6 Ice Worlds https://www.bbc.co.uk/iplayer/episode/b0074t1d/planet-earth-6-ice-worlds and
Planet Earth ep 8 Jungles https://www.bbc.co.uk/iplayer/episode/b0074tgb/planet-earth-8-jungles

only download as SD - they show up in Get iPlayer Automator as Editorial but are available for download on the respective pages as HD.

All the other episodes in the series download as HD ok though. https://www.bbc.co.uk/iplayer/episodes/b006mywy?suggid=b006mywy

**Comment by jefro108** [comment]
It's probably a help to have a log https://gist.github.com/jefro108/56d71eb57e12ed5edbfcd61448273487

It appears that version 'editorial' is only available in SD but 'editorial2' is available in HD, however 'editorial' is the one chosen for download.

Any reason why this might be the case? Is it possible to check and download the HD version?

**Comment by skovatch** [comment]
This sounds more like a get_iplayer bug than GiA, but I think you can work around it in GiA by tweaking the default preferences. 

Looking through the source, gip has a list of default versions.

`my @default_version_list = qw/original iplayer technical editorial lengthened shortened opensubtitles/;
`
My guess is that get_iplayer is using that list to decide which version to search for, and since you've specified a mode of tvbetter, that matches so it downloads the SD version.

You could try just specifying 'Best' as the only mode for BBC just for downloading that program. Alternatively, you could the write to the preferences and tell get_iplayer to look at 'editorial2' first.

`get_iplayer --prefs-add --versionlist=editorial2 --profile-dir="/Users/<your username>/Library/Application Support/Get iPlayer Automator"`

**Comment by jefro108** [comment]
Thanks for this help.

I tried just specifying  'Best' as the only mode for BBC but it still wanted to download the SD version!

However adding the User Preference did the trick, by including editorial2.

I ended up using 

`get_iplayer --prefs-add --versionlist=editorial2,editorial --profile-dir="/Users/<your username>/Library/Application Support/Get iPlayer Automator"` since one of the above programmes wouldn't download with `editorial2` but did with `editorial`.

I was wondering though whether it would be good to keep the `editorial2` in the list for general downloading, but it appears that this preference overrides `@default_version_list`.

**Comment by skovatch** [comment]
This appears to have been fixed in get_iplayer 3.19, according to the [release notes](https://github.com/get-iplayer/get_iplayer/wiki/release310to319#release319). GiA now includes get_iplayer 3.20, so I'm closing this. Let me know if it comes up again.
