### ISSUE TITLE
question: wildcards for BBC channel

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#236]
Hi,

I am trying to download Shetland and I have noticed in my PCV that I have an entry for both "BBC One" and  "BBC Four".

I have quite a lot of entries so have been trying (without success) to reduce these kinds of entries to just one.  I have tried
 BBC
 BBC*
 BBC *

...neither will find Shetland.  Is there a way to do this?

**Comment by jchhenderson** [comment]
To add, I know I can use "*", but this searches ITV as well and I assume slows the process down and risks false positives.

**Comment by skovatch** [comment]
So, I'm not completely sure I'm going to be answering your exact question, but here goes:

Unfortunately, in GiA there's no way to use a wildcard for searching anything other than the show name. 

Looking at the source for get_iplayer, it looks like they don't separate BBC Radio Shetland as its own channel -- it's lumped in with BBC Radio Scotland. Normally that would mean you should check the "Show Regional Radio Stations", but the code currently doesn't know to look for "BBC Radio Scotland"

As a short-term fix, you could check "Show Local Radio Stations", since that's the catch-all for anything that isn't in the known list of national or regional channels.

The BBC channel filtering logic hasn't been touched in some time. I'm seeing channels that either have been renamed or were discontinued, so the checkboxes won't filter anything. I'll look into that.

**Comment by skovatch** [comment]
Let's start over by helping me clarify what you're asking for here. Are you referring to the PVR Manager window, and then then "Series-Link" section? 

The implementation of the wildcard operator in that field is not very smart. It's either a exact text match or '*', which searches all channels. "BBC *" will try to match the literal string "BBC *", which of course, won't work.

I would suggest putting "BBC Radio Scotland" in that field, since as mentioned above, get_iplayer no longer distinguishes BBC Radio Shetland from BBC Radio Scotland.

**Comment by jchhenderson** [comment]
Hi,

Thanks for you replies :-)

"Shetland" is the name of the BBC show I was trying to download (not the radio station) and it has been on both "BBC One" and "BBC Four" in the past - I think "BBC Four" was for repeats..

Yes, I was referring to the "TV Network" in the PVR manager - sorry I was not clear about this.

You answered my question perfectly with this:
> The implementation of the wildcard operator in that field is not very smart. It's either a exact text match or '*', which searches all channels. "BBC *" will try to match the literal string "BBC *", which of course, won't work.

Thanks!
James.

**Comment by skovatch** [comment]
OK, glad I could help. It motivated me to look at part of the code that hadn't been touched in a while, so it's good all around.
