### ISSUE TITLE
Feature request - remove BBC Series number from title.

### ISSUE THREAD

**Issue by eloise-pet** [Ascoware/get-iplayer-automator#269]
Unless I'm doing something silly; most BBC downloads have Series # as part of the series name.

For eg. Doctor Who: Series 11

Is it possible for get-iplayer-automator to strip this out automatically rather than me having to manually?

Thank you (and sorry if I've posted something I shouldn't have done)

**Comment by skovatch** [comment]
Feature enhancements are always welcome! I may not reply to every one and I may not get to them, but I always read them.

This happens because the default naming pattern is `<name> - <episode> ((<modeshort>))`, which expands to the full "Series x - EpisodeNumber EpisodeTitle". 

We could look into having a user-defined format string, but that could be a bit more complicated than I want for the UI. You might want to try the 'Use Kodi (XBMC) naming' option, which is more compact but might be too terse for your needs.

**Comment by eloise-pet** [comment]
Thanks for your reply... great utility and thanks for the work.

The file naming is fine, just in iTunes the series name (from the mp4 metadata) contains the series number. It’s not an end of the world thing, just nice to avoid.

Thank you.
