### ISSUE TITLE
Unable to find any BBC shows in search

### ISSUE THREAD

**Issue by ffooky** [Ascoware/get-iplayer-automator#27]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Searching for any BBC show

*What is the expected output? What do you see instead?*

I'd expect a list of results but after what seems a long search I get the "No Shows Found" window

*What version of GiA are you using? On what version of OS X?*

1.9b6 on 10.9.5 (no developer tools or special Perl etc, a vanilla install)

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No, no, no and no

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

Eastenders

*Please provide any additional information below.*
Everything is fine using Use Current Webpage
[Verbose Log.txt](https://github.com/Ascoware/get-iplayer-automator/files/999226/Verbose.Log.txt)

**Comment by gingerbeardman** [comment]
The only way I can reproduce this is for me to disable all channels in the cache.
If that's the case then search should be aware that there is no cache and disable itself?

Are you sure you've got some channels caching and that the cache has finished downloading?

Here's the search working for me.
![screen shot 2017-05-15 at 13 19 44](https://cloud.githubusercontent.com/assets/49612/26057355/37d47f86-3971-11e7-8fec-0801d26bce29.png)

**Comment by ffooky** [comment]
Yes, all channels are set to cache and the sequential indexing etc has finished though it does seem to take a very long time on either of the machines I have here (both 10.9.5). Here's a grab of Little Snitch while the indexing is underway.
![screenshot 2017-05-15 13 35 21](https://cloud.githubusercontent.com/assets/18357388/26058215/c7167084-3974-11e7-98d6-186a93a75799.png)

**Comment by gingerbeardman** [comment]
Get you try:

* quit app
* trashing support folder `~/Library/Application Support/Get iPlayer Automator`
* re-launch app
* set channels to cache
* force cache update
* wait
* search

**Comment by ffooky** [comment]
I've done that before but tried again. No dice. I was watching the log after the ITV index had finished, whilst the long indexing was underway and the next line was ”INFO: 0 Matching Programmes" which was before I'd even attempted a search so I'm guessing 5hats a good indicator of where the prob lies. Thanks very much for your help on this
![screenshot 2017-05-15 15 46 12](https://cloud.githubusercontent.com/assets/18357388/26063686/a0d42ab2-3986-11e7-8bcc-bde2db9acdf4.png)

**Comment by gingerbeardman** [comment]
@ffooky can you please try just radio and no TV channels?

**Comment by ffooky** [comment]
Same result I'm afraid

**Comment by gingerbeardman** [comment]
Good point.

Could be related to https://github.com/Ascoware/get-iplayer-automator/issues/15 ?

**Comment by neeklamy** [comment]
I’m getting really spotty results, despite forcing the cache to update.

Search for `news quiz` or even just `quiz` and it finds the [News Quiz Extra episode 4](http://www.bbc.co.uk/programmes/p0530vlq) broadcast on Radio 4 Extra, 15 May 2017.

Search for `isy` or `suttie` or anything up to and including the full title, and it **can’t find** [Isy Suttie’s Guide to the Family](http://www.bbc.co.uk/programmes/b06r9b2t) broadcast on Radio 4 Extra, 13 May 2017.

Going through some of the Radio 4 Extra schedules, the only programme I found available on [Saturday 13 May 2017](http://www.bbc.co.uk/radio4extra/programmes/schedules/2017/05/13) was Simon Bovey - Cold Blood.

Sunday was no better (I checked a random selection), [Monday 15 May](http://www.bbc.co.uk/radio4extra/programmes/schedules/2017/05/15) seems to be entirely available – it seems through this *very* unscientific approach to be a week based problem, no or very few Radio 4 or 4 Extra programmes from the previous week are available.

**Comment by gingerbeardman** [comment]
I notice that when doing the cache update the app uses "concurrent indexing", apparently for speed, and the command line uses "sequential indexing" so I wonder if there's an issue there?

**Comment by elflife** [comment]
![20170517-no show found](https://cloud.githubusercontent.com/assets/15110555/26128597/83e57016-3abf-11e7-8344-9a6dd03710b0.png)
Can add by "use current web page" and download, can't find the program by search.

**Comment by pmhird** [comment]
This is exactly the same for me, also on 10.9.5. Downloads work fine if I use "use current webpage" but no items found in search, and no series link auto-added to queue. I have already tried deleting the library file, and forcing cache update but it makes no difference. Same result in 1.9b1 or 1.9b2 for me. I have gone back to 1.9b1 because it seemed to offer more stable downloading. 1.9b2 sometimes crashed mid download for me. Could these be 10.9.5-specific issues?

**Comment by gingerbeardman** [comment]
What does the your log say related to caching? 
Might help to have Verbsose switched in in preferences.

I get this after successful caching:

`Get iPlayer Automator 1.9b6 Initialized.

AppController: Updating Programme Index Feeds...

INFO: Getting radio Index Feeds (this may take a few minutes)
INFO: Using concurrent indexing
AppController: Index Updated.
`

and this after searching for "radcliffe"
`
/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer.pl
--nocopyright
-e60480000000000000
--type=radio
--listformat=SearchResult|<pid>|<timeadded>|<type>|<name>|<episode>|<channel>|<seriesnum>|<episodenum>|<desc>|<thumbnail>|<web>
--long
--nopurge
radcliffe
--profile-dir=/Users/matt/Library/Application Support/Get iPlayer Automator`

**Comment by neeklamy** [comment]
Verbose logging enabled, relaunched Get iPlayer Automator just to make sure it fetches any more programmes.

```
Get iPlayer Automator 1.9b6 Initialized.

AppController: Updating Programme Index Feeds...

AppController: Index was Up-To-Date.
```

Search for `radcliffe` (*fond memories, how I loved Mark and Lard*) and just three results come up.

```
Get iPlayer Automator 1.9b6 Initialized.

AppController: Updating Programme Index Feeds...

AppController: Index was Up-To-Date.
/Users/chris/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer.pl
--nocopyright
-e60480000000000000
--type=radio
--listformat=SearchResult|<pid>|<timeadded>|<type>|<name>|<episode>|<channel>|<seriesnum>|<episodenum>|<desc>|<thumbnail>|<web>
--long
--nopurge
radcliffe
--profile-dir=/Users/chris/Library/Application Support/Get iPlayer Automator
```

Would I be better off just blowing away all caches and preferences at this point?

**Comment by skovatch** [comment]
@neeklamy Yes, delete the folder /Users/chris/Library/Application Support/Get iPlayer Automator and relaunch.

**Comment by ilainftw** [comment]
@ffooky, @neeklamy, et al. - You have gotten the runaround from somebody who clearly doesn't know how things work, and who is apparently unwilling to do some homework. This is a case where no advice would have been better than such poor advice. Let's start over, shall we? 

Your problems have nothing to do with preferences, the contents of the Application Support folder, channels to cache, #15, or anything else you were told above.  You have run into two things here:

1. There is a bug in the the HTML::Parser module provided in the built-in Perl on 10.9. It breaks on many BBC pages and the end result is that  those pages are truncated, resulting in few or no cache entries.

2. The developer doesn't tell you how to set up GiA so that concurrent indexing (which is much faster, but required Mojolicious) is enabled. Concurrent indexing  provides a solution to the first problem, though you should still update HTML::Parser as well.

Basically, you need to install a couple of Perl modules where the built-in Perl (GiA is hardwired to use this) can find them. There are different ways to go about this. I used a straightforward, though slightly more intrusive method. There is a less-intrusive, hackier method, but it relies on what is a bug, or at least an oversight, in GiA, so I don't want to steer you in that direction to start. 

Because it uses sudo, this method installs Perl modules under /Library/Perl/5.16 and other files under /usr/local. If you are using Homebrew, beware of the latter. If you have already installed cpanminus via Homebrew, you shouldn't need to reinstall it. The other modules shouldn't conflict with anything installed via Homebrew. Take some time to Google on this if you have any doubts.

```
# install cpanminus - always handy and can be used to uninstall modules
# If this is the first cpan run, you will be prompted to create a list of CPAN 
# download mirrors - you should be able to accept the defaults
sudo cpan -i App::cpanminus
# use cpanminus to install the additional modules
sudo cpanm HTML::Parser Mojolicious
# if you need to back out module installation
sudo cpanm --uninstall HTML::Parser Mojolicious
```

Now quit GiA if open and back up and delete the tv.cache and radio.cache files in the Application Support directory. Relaunch GiA and let the caches refresh. It should go noticeably faster. You should see "Using concurrent indexing" in the GiA progress display and hopefully a full cache when finished.

**Comment by ilainftw** [comment]
@ffooky, @neeklamy, et al. - Sorry, I fat-fingered and left out the most important instruction. Before anything else, install the Xcode command line tools (compilers etc. needed for building Perl modules) by running `xcode-select --install` and following the instructions. Once the tools are installed, install the modules as I described above.

**Comment by ffooky** [comment]
@ilainftw Absolutely awesome, thanks very much, worked like a dream.

**Comment by gingerbeardman** [comment]
@ilainftw great detective work, thanks!

**Comment by ilainftw** [comment]
For this and all issues: Stop telling people to delete the application support folder. That will never be the right answer for these problems, and may be harmful. Anyone with a full BBC cache will lose half of it if they delete that folder and haven't backed it up, and GiA provides no easy means to regenerate the lost data. Take a breath and learn how GiA and get_iplayer work before proffering advice.

**Comment by gingerbeardman** [comment]
@ilainftw how patronising 😳

**Comment by ilainftw** [comment]
Take your medicine and do your homework, or leave GiA to the grown-ups. You don't help anyone when you send them on wild goose chases or tell them to destroy their data.

**Comment by gingerbeardman** [comment]
@ilainftw 🤣

**Comment by skovatch** [comment]
All right @ilainftw, this is your warning: I will not tolerate assholes in this project. I will start deleting your comments, helpful or otherwise if you can't be respectful of others. I don't know much about perl, and quite frankly, don't want to spend a lot of time on it. If you want to offer help, by all means do so, but I have no patience for patronizing jerks.
