### ISSUE TITLE
Subtitles not downloaded but available with get_iplayer

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#272]
Sometimes subtitles don't get downloaded and I get the message in the log:

```
ERROR: Response: 403 Forbidden
ERROR: Access to this resource was blocked by the BBC
ERROR: Ignore this error if programme download is successful
ERROR: Subtitles download failed
ERROR: Use --subtitles-only to re-download
WARNING: --subs-embed specified but subtitles file not found: /Volumes/media/Downloads/TV Shows/Father Brown/Father Brown.s08e04.The Wisdom of the Fool.srt
INFO: Converting to MP4
```
but when I used get_iplayer to download them with

`get_iplayer --subtitles-only --pid=m000d2sn
`

as was suggested, they did download.

Maybe GIA could include another step to redownload the subtitles if they don't for some reason get downloaded the first time?

Using latest version of GIA on Mojave

See full log 
[GIAsubtitleserror.txt](https://github.com/Ascoware/get-iplayer-automator/files/4045779/GIAsubtitleserror.txt)
and full response from get_iplayer
[get_iplayer-subs.txt](https://github.com/Ascoware/get-iplayer-automator/files/4045803/get_iplayer-subs.txt)

**Comment by ElsonRoa** [comment]
FWIW, I'm getting the same error on GIA Version 1.17 (20191130002), OSX 10.13.3 High Sierra. GIA does not DL subs but I can get them through terminal with the command get_iplayer --subtitles-only .

I'd speculate this may be due to some sort of change at the BBC's end because the error did not occur after any kind of software update.

**Comment by MistressMB** [comment]
I'm also getting the same issue on GIA Version 1.17 (20191130002) on OSX Mojave 10.14.6 (18G2022). I agree with ElsonRoa, this issue started appearing recently with no apparent change from GIA.

**Comment by skovatch** [comment]
Sorry for the delay in replying -- iCloud started filtering my email into random folders last week.

Looks like get_iplayer 3.25 was released on 1-February, which should fix the 403 errors. I'll post an update when I get some free time.

**Comment by jefro108** [comment]
Great, thanks 😊

**Comment by hugofalkman** [comment]
FWIW I am NOT getting any subtitles download failures on GiA 1.17 (20191130002) and macOS Catalina 10.15.3. Have downloaded quite a few BBC programs with subtitles since 1 February including all ten episodes of the new third season of Shakespeare & Hathaway.

In the log there are now always plenty of error 403 forbidden messages, followed by ignore this error if download successful, but in no cases do the downloads actually fail.
