### ISSUE TITLE
HD downloads failing half way through.

### ISSUE THREAD

**Issue by arijitsadhu** [Ascoware/get-iplayer-automator#28]
Downloading Versailles series 2 episode 1, hlsvhigh (1280x720) downloads to 48% then fails and restarts downloading as hlsxstd (960x520). Every other episode downloaded as 1280x720. Not sure if it is a BBC problem.  

Using GIA 1.9b4 on macos 10.12.

**Comment by raythw** [comment]
I believe this to be a BBC streams problem, as I've had this happen with GetiPlayer as well. It's one reason I asked for the 50FPS streams to be available in GiA, since these often work when the hlsvhigh stream is missing. BTW, my thanks for the 50FPS option having been provided! I can only suggest you wait a while until the stream eventually appears, assuming it does, of course, or try 50FPS.

**Comment by mutantcamel** [comment]
If there error is "File segment not available from server" then it's a broken stream at the BBC end, nothing get_iplayer can do about it.  Check https://github.com/get-iplayer/get_iplayer/wiki/issues for more info.

**Comment by skovatch** [comment]
As others have said, this isn't a GiA issue, it's a BBC problem. Thanks for the reference to the get_iplayer wiki.
