### ISSUE TITLE
Series-Link to Queue does not work for "new" ITV shows that have Series in the title

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#328]
**What steps will reproduce the problem? Be specific, and provide as much detail as possible.**

In the past, Auto-recording an ITV show would result with only the title of the show in the "show" column of the PVR.  BBCi would result with both Show and series in the title column.

Since the last change, ITV now also puts both the Show and Series in the title as well.  However, it is missing a lot of matches as a result.  When I edit the Show's name removing the Series info, it matches again.

**What is the expected output? What do you see instead?**
Expected: Shows being added to Queue
Instead: Shows are being missed

**What version of GiA are you using? On what version of OS X?**
GiA: 1.21.7
OS: 11.2.3

**Are you using a web proxy? DNS proxy? VPN? VPS?**
No.

**What program are you attempting to download (full title, series and episode)?**
"Superstore: Season 6" in the PVR misses finding Superstore s06e02
"Superstore" in the PVR finds s06e02

*Please provide any additional information below.*
There is something wrong with ITV matching when season is in the Show column of the PVR, but not in the show column of the queue:
![Screenshot 2021-04-21 at 11 11 28](https://user-images.githubusercontent.com/34644672/115537555-d5279c80-a292-11eb-96f5-4c2cbbd09623.png)

**Comment by howyallare** [comment]
This is a bug in 1.21.7. The ": Season 6" is appended to ITV show name in search results, but it isn't stripped when item is added to Series-Link list. Any later PVR search fails because ": Season 6" isn't part of the programme name in ITV cache. I suppose it could be parsed and the season number used to constrain the search, but I can't say if that would be worth the effort. There isn't much you can do for now except what you're already doing: editing ITV Series-Link entries.

**Comment by jchhenderson** [comment]
That’s a shame as I deleted literally 100’s of entries in my download history as they were only necessary as long as the show name did not have the series number associated with it,

**Comment by howyallare** [comment]
If you have a backup of the download history file you should be able to reconcile pretty quickly.

**Comment by jchhenderson** [comment]
actually, I am just going to recover the `Queue.automatorqueue` and `download_history` from 2 days ago and then check the downloads since then.

**Comment by jchhenderson** [comment]
...and done!

**Comment by skovatch** [comment]
This is fallout from the whole showName/seriesName mess I tried to fix earlier. When creating the cache I wasn't appending the ": Series x" to the series name, so we had to add it back after a search. But auto-record uses showName for its search, so as noted, it won't be found. 

Adding ": Series x" to the cached show name fixes the problem and simplifies the code a bit because get_iplayer does the same for the cache of BBC shows.

**Comment by jchhenderson** [comment]
I'd prefer to keep the ": Series x" if possible as it means I can reduce the download history with episodes from different seasons to the one I want.

**Comment by skovatch** [comment]
Right, the change is to put it back in the cached show name so it can be found later with auto-record.

**Comment by jchhenderson** [comment]
fantastic - thanks!

**Comment by skovatch** [comment]
Fixed in v1.21.9

**Comment by jchhenderson** [comment]
...of course, downloading any ITV content doesn't work right now (I know this is out of your hands).
