### ISSUE TITLE
ITV Caching 

### ISSUE THREAD

**Issue by chazf1** [Ascoware/get-iplayer-automator#4]
Firstly a big thanks to all for the time and effort to bring GIA back to life.

The issue I have is I'm unable to search for ITV programmes in GIA1.9b1
ITV programme downloads only available via webpage.
I have tried using the Advanced tab/Alternative ITV Cache but all searches result in "No Shows Found"

GIA 1.8.8-pre5 still indexes and searches current ITV content. 

Any chance to have a look into this?

**Comment by Vangelis66** [comment]
Not a GiA user, but an advanced GiP user since 2010... 
What you're experiencing is because: 

1. GIA 1.8.8-pre5 still uses GiP 2.94 (currently broken for BBC fetches)
2. GiP 2.94 has built-in support for "external" plugins.
3. GIA 1.8.8-pre5 uses an old (from 2009) GiP itv.plugin that populates the ITV cache.
4. GiA 1.9b1 now uses GiP 3.01 for BBC fetches, but support for "external" plugins 
has been withdrawn in GiP 2.98+, see 
https://github.com/get-iplayer/get_iplayer/commit/b311e70

So in order for what you ask to be restored, new maintainer 
must first bring back "external" plugin functionality to GiP 3.01, 
so it could use again itv.plugin... 
BTW, as a standalone GiP 3.01 user (on Windows) I'll also 
be interested in such a development (I used to use GiP 
to browse ITV offerings...) 

Good luck to the new owner :+1:

**Comment by Vangelis66** [comment]
... In addition to my previous comment, the ITV.cache issue in new GiA versions, utilising new GiP scripts,  
has been mentioned in the following original repo comment: 

https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/632#issuecomment-298673078

HTH 😄

**Comment by skovatch** [comment]
Working now in 1.9b2. App fetches ITV shows and can search the cache.

I use the ITV plugin so that get_iplayer knows that ITV shows exist. It doesn't do the actual fetching, however.

**Comment by Vangelis66** [comment]
@skovach wrote: 

> I use the ITV plugin so that get_iplayer knows that ITV shows exist. 
> It doesn't do the actual fetching, however.

Thanks, I already knew that; ITV downloading is delegated to 
specialised code inside GiA, not a GiP thing :-(
TBH, it has always been a wishful thinking of mine 
that some kind person with required perl-fu could patch itv.plugin 
to handle ITV downloads, too. 
It's a real shame, though; up until GiP 2.99, all the available utilities 
for ITV downloads were included (RTMPdump to fetch RTMP streams - 
ITV uses those, FFmpeg to remux FLV files to MP4 container, AtomicParsley 
to tag those MP4 files, possibly including a thumbnail, too...).
Sadly I can't code myself, thus a wishful thinking it will remain :sob: 

Best wishes for your new endeavour!

**Comment by pmhird** [comment]
I've got the 1.9b2 but my ITV searching and PVR collecting doesn't work. It takes a massive amount of time to search and then returns no shows what ever I search for. Is there an additional pug in I need to install? It also seems to take ages to do anything, like start a download. And just now it failed a BBC download, despite it working previously nicely on 1.9b1. What have I done wrong guys and how do I fix it?! (OSX 10.9.5)

Thanks for all the help so far.

**Comment by rogercuthbert** [comment]
Just for info. I am running MacOs 10.12.4 and using GiA 1.92b2 is working ok.  Just searched and downloaded a BBC and ITV news programme successfully.  Both updated into iTunes.    Well done everyone, greatly appreciated.
