### ISSUE TITLE
File naming - possible improvement

### ISSUE THREAD

**Issue by botchla** [Ascoware/get-iplayer-automator#57]

**Comment by botchla** [comment]
Not sure if this suggestion is easy/possible or whether it would benefit anyone but me, but if, when the XBMC naming option is selected, the filesnames could have something like '720p' or '576p' included (depending on which quality and resolution had been downloaded) it would be a big help to me.

Would be interested to know what others think.

**Comment by XYZeb** [comment]
+1 from me. As a workaround, you can use Column view in finder, which shows dimensions in the file preview/summary on the right but in the filename would be nicer.

**Comment by skovatch** [comment]
The best that can be done, I think, is to add <.modeshort> when XBMC is being used. This would cause get_iplayer to add the version it downloaded into the file name, so for example:

Pointless Celebrities.s10e18.Experts.hvfxsd.mp4

It has to be up to get_iplayer to figure this out, since it handles the actual download and creation of the file. All GiA does is scrape the name of the final output file.

I'm not sure you want resolution anyway -- as I read their spec, XBMC (Kodi) says it will strip away that information when it imports the file.

**Comment by botchla** [comment]
Thanks, Scott. For me, it's more to do with recognising resolution when I import files using Sonarr. I think your solution will help in my case. Great work on GiA!

**Comment by chewitt** [comment]
Kodi does not require resolution info to be in the filename as it automatically analyses media and detects these params when scraping content to the library. Most Kodi skins show this flagging if available. If you want to create "scene" filenames please do this as a separate naming option instead of polluting the original (deliberately simple) Kodi naming.

**Comment by botchla** [comment]
@chewitt I totally get your points, although I process the filenames it produces to replace full stops with spaces, capitalise the S and E in the episode info and a few other things before giving them to Kodi/Plex anyway. Can't speak for everyone, but for me, the Kodi naming option is most useful in its inclusion of the season and episode numbers (and now, for me personally at least, basic resolution info).

**Comment by chewitt** [comment]
I'm the original requester of the XBMC naming feature and I worked with the original app creator to set a naming scheme that optimises human readability and scraping accuracy; we in the Kodi team have done tests on this stuff. Adding scene tagging to filenames has been proven to reduce scrape accuracy (which is why content stealing tools do their best to auto-rename scene files). So, please revert this idea and put things back how they were. And if something is really necessary, make it optional so the many existing users who do not have to rename all their files are not inconvenienced for the benefit of the few who want this.

**Comment by botchla** [comment]
Fair enough @chewitt, and thanks for the explanation. Sorry, @skovatch - it was not my intention at all to cause issues for others.
